### ISSUE TITLE
Progress Tracking

### ISSUE THREAD

**Issue by budak7273** [Jarno458/SatisfactoryArchipelagoMod#1]
# This issue's checklist is being phased out in favor of https://github.com/users/Jarno458/projects/3/views/1 so this will likely be out of date

## Server (https://github.com/Jarno458/Archipelago/tree/Satisfactory):

- [x] Add alumina support to server side (I skipped this entire build chain mostly)
- [x] Add power infrastructure logic to server
- [x] Add logic for logistics to server (so the server has a reason to give you access to faster belts)
- [x] Add Mam locations + logic
- [x] Add Utility buildings to server / client (e.g. Power poles, logistics, awesome shop, bp designer)
- [x] Add Recipes for equipment (current only available as item but never unlocked to craft)
- [ ] Add Schematics for grouped items, like all walls\roof, all pipes, all train pieces
- [ ] Redo everything in a performant way
- [x] Automatic MAM location data export for server from client

## Client:

- [x] Add item output to ApPortal
- [x] Make ApPortal respect power requirements 
- [x] Disable ApPortal input belt
- [ ] Add update mam tress with randomized researches from server
- [x] Add hub milestone purchase costs to server and send to client 
- [x] Send final space elevator tier to client, and make client send the completed signal when its reached 
- [x] Free Samples via [separate mod](https://github.com/budak7273/FreeSamples)
- [x] Update Energy Link implemenation 
- [x] Optional: implement sending items using ApPortsl input belt
- [x] Add Utility buildings to server / client (e.g. Power poles, logistics, awesome shop, bp designer)
- [x] Add Recipes for equipment (current only available as item but never unlocked to craft)
- [ ] Add Schematics for grouped items, like all walls\roof, all pipes, all train pieces
- [ ] Award inventory slots
- [x] UI for Archipalgo building
- [x] Continue from existing save

## Future Ideas
 - [ ] Ore node randomization
 - [x] Spawn enemies as traps
 - [ ] Sinksanity - Change AWESOME Sink point values of items, probably suggest having [TFIT](https://ficsit.app/mod/TFIT) installed so they can be viewed
 - [ ] Add server support for harddrive gacha
 - [ ]  Supports collectalbles: Summersloop or Mercer sphere
 - [ ] ~~Golden Nut statue goal?~~ obsoleted by coupon count goal
 - [ ] Trap: Brownout (fuse trip all power networks)
 - [ ] Trap: Fake brownout (play the brownout sound and UI, but don't actually shut down any power networks)
 - [ ] Trap: Off (randomly turn off N machines)

**Comment by Jarno458** [comment]
- [ ] Add Utility buildings to server / client (e.g. Power poles, logistics, awsome shop, bp designer)
- [ ] Add Recipies for enquipment (current only avaiable as item but never unlocked to craft)
- [ ] Add Schematics for grouped items, like all walls\roof, all pipes, all train pieces

**Comment by Jarno458** [comment]
This is now mostly moved to a project board: https://github.com/users/Jarno458/projects/3
